plugins {
  id 'com.android.library'
  id 'org.jetbrains.kotlin.android'
}

apply from: "${rootDir}/engine/versions.gradle"

android {
  namespace 'dev.pampa.fluidweather.core.data'
  compileSdk engine.compileSdk

  defaultConfig {
    minSdk engine.minSdk
  }

  compileOptions {
    sourceCompatibility engine.javaVersion
    targetCompatibility engine.javaVersion
  }

  kotlinOptions {
    jvmTarget = engine.jvmTarget
  }
}

dependencies {
  testImplementation "junit:junit:${engine.junit}"
}
