plugins {
  id 'com.android.library'
  id 'org.jetbrains.kotlin.android'
}

apply from: "${rootDir}/engine/versions.gradle"
apply from: "${rootDir}/versions-app.gradle"

android {
  namespace 'dev.pampa.fluidweather.core.sensor'
  compileSdk engine.compileSdk

  defaultConfig {
    minSdk engine.minSdk
  }

  compileOptions {
    sourceCompatibility engine.javaVersion
    targetCompatibility engine.javaVersion
  }

  kotlinOptions {
    jvmTarget = engine.jvmTarget
  }
}

dependencies {
  api project(':core-data')

  implementation "androidx.core:core-ktx:${engine.coreKtx}"
  implementation "androidx.work:work-runtime-ktx:${appVersions.work}"
  implementation "com.google.android.gms:play-services-location:${appVersions.playServicesLocation}"
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:${engine.coroutines}"
  // L'await() sui Task di Play Services.
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:${engine.coroutines}"

  testImplementation "junit:junit:${engine.junit}"
}
